// Generated by Wrangler on Sun Apr 21 2024 13:41:12 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	MY_KV_NAMESPACE: KVNamespace;
}
